### ISSUE TITLE
Web App

### ISSUE THREAD

**Issue by haithamRD** [codeglitchz/attendance-system#8]
hey sir , 
did you work this application in web.
if yes you can share the source code please
email: haitham.rdina@gmail.com

**Comment by codewhizz** [comment]
Hello @haithamRD,
The web app code is under development #6. First we will add a login and signup page. Our designers are working on the User Interface part.
We would also love to have some suggestions about the design of our web app. So keep yourself updated with this repository =)

**Comment by codewhizz** [comment]
Released v2.0.0 with Web App Included

**Comment by haithamRD** [comment]
hey i m create a web app  for recognition
